title: BroadcastStorm
description: "A maelstrom of network, systems, and software engineering."
permalink: ':title/'
baseurl: ""
url: "https://broadcaststorm.github.io"
site-twitter:

# Author Settings
author: Tim Miller
author-img: tim_miller_social.jpg # add your photo
about-author: I enjoy learning, doing, and explaining complex topics from physics to Linux to networking to cloud. My path has included journeys as a scientist, systems engineer, and IT architect.
social-twitter: broadcaststorm
# social-facebook:
social-github: broadcaststorm
social-linkedin: timothyemiller
# social-email:

# Disqus
discus-identifier:

# Tracker
analytics: 

# Build Settings
markdown: kramdown
remote-theme: artemsheludko/flexible-jekyll
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-footnotes

paginate: 8
paginate_path: "/page/:num"

preview: 40

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
